[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "boto3>=1.40.21",
    "ipdb>=0.13.13",
    "pytest>=8.4.1",
    "requests>=2.32.5",
]
